### ISSUE TITLE
Support Python’s “unittest” framework

### ISSUE THREAD

**Issue by vadmium** [reingart/pyfpdf#12]
Recently I pushed some changes to allow using the existing test suite with Python’s “unittest” framework. This issue is to allow the changes to be discussed and reviewed better.

Comparison of the changes: <https://github.com/reingart/pyfpdf/compare/25af257...dd64bb1>

The tests may now be run on Python 2.7 and 3.2+ with a command like

    python -m unittest discover -s tests/cover/

The main advantages for using “unittest” for me are:

* Familiarity, e.g. I know how to specify different interpreters, enable warnings, etc
* Better exception reporting when a test fails

The original “runtest.py” script that runs all the tests on different Python interpreters should continue to work as before. Also, individual test files can still be run as before. So nothing is lost. The advantages for these methods:

* “runtest.py” automatically uses various Python interpreters
* Better support for older Python versions

In the standard “unittest” library that comes with Python 2.5 and 2.6, the automatic test discovery mode is not supported, so it may not be so useful in those Python versions. There might be a separate package that could be installed, but this would need more investigation.

**Comment by RomanKharin** [comment]
unittest works!
We definitely should create descriptive wiki page.
runtest.py - use all available interpreters, show compact result
unittest - more standart way, show unclosed files and deprecations warnings

**Comment by vadmium** [comment]
Yep, this could be added to the Testing wiki page, perhaps after we get an idea of what is happening with the wiki pages and Google Code migration.

**Comment by RomanKharin** [comment]
Note:
runtest - creates files in tests/out-***
unittest - files created in current folder

**Comment by RomanKharin** [comment]
Hi to all.
Recently i  slightly update old wiki pages from google code and merged them into docs folder.
For now all information about testing can be obtained from https://github.com/reingart/pyfpdf/blob/master/docs/Testing.md
