### ISSUE TITLE
FPDF Put Images KeyError: 'data'

### ISSUE THREAD

**Issue by lyjen** [reingart/pyfpdf#157]
![fpdf put images del info](https://user-images.githubusercontent.com/3081235/87132684-d02bca80-c2c8-11ea-9e91-3f36049e6f32.png)

Anyone who can help me about FPDF error because I was trying to regenerate PDF, but got the following FPDF error:
```  File "/usr/local/lib/python3.5/dist-packages/fpdf/fpdf.py", line 1230, in output
    self.close()
  File "/usr/local/lib/python3.5/dist-packages/fpdf/fpdf.py", line 322, in close
    self._enddoc()   # close document
  File "/usr/local/lib/python3.5/dist-packages/fpdf/fpdf.py", line 1868, in _enddoc
    self._putresources()
  File "/usr/local/lib/python3.5/dist-packages/fpdf/fpdf.py", line 1791, in _putresources
    self._putimages()
  File "/usr/local/lib/python3.5/dist-packages/fpdf/fpdf.py", line 1706, in _putimages
    del info['data']
KeyError: 'data'

Data has nothing to do with the pdf template as it seems the issue coming here
 def _putimages(self):
        filter=''
        if self.compress:
            filter='/Filter /FlateDecode '
        i = [(x[1]["i"],x[1]) for x in self.images.items()]
        i.sort()
        for idx,info in i:
            self._putimage(info)
            del info['data']
            if 'smask' in info:
                del info['smask']

Thanks

**Comment by alexanderankin** [comment]
without even looking into the issue further, the https://pypi.org/project/fpdf2 implementation relies on pillow for image processing

**Comment by lyjen** [comment]
> without even looking into the issue further, the https://pypi.org/project/fpdf2 implementation relies on pillow for image processing

oh thanks, will try it first
Thanks Alex

**Comment by lyjen** [comment]
Hi @alexanderankin ,

I already installed the FPDF2 using pip3 but I still got the same issue. Not sure if overwrites the old fpdf. Thanks for your help.

**Comment by mslyjen** [comment]
It's already solved! Thanks a lot.

**Comment by lyjen** [comment]
It's already solved! Thanks a lot.
