### ISSUE TITLE
AttributeError: 'FPDF' object has no attribute 'orientation_changes' when using set_link

### ISSUE THREAD

**Issue by Lucas-C** [reingart/pyfpdf#159]
The error I get:
```
Traceback (most recent call last):
  File "./gen_pdf.py", line 20, in main
    pdf.output('out.pdf', 'F')
  File "/opt/pyfpdf/fpdf/fpdf.py", line 1110, in output
    self.close()
  File "/opt/pyfpdf/fpdf/fpdf.py", line 270, in close
    self._enddoc()
  File "/opt/pyfpdf/fpdf/fpdf.py", line 1688, in _enddoc
    self._putpages()
  File "/opt/pyfpdf/fpdf/fpdf.py", line 1210, in _putpages
    if l[0] in self.orientation_changes:
AttributeError: 'FPDF' object has no attribute 'orientation_changes'
```

The function I use to add links:
```
def link_to_page(pdf, page_id, x, y, width, height):
    link = pdf.add_link()
    pdf.set_link(link, page=page_id)
    pdf.link(x, y, width, height, link)
```

I am working on a PR to fix this.

**Comment by Lucas-C** [comment]
The PR: https://github.com/reingart/pyfpdf/pull/160

**Comment by rikiNeustadt** [comment]
I have the same issue.
How can I install the fix with pip? (or other recommended way).
this module installed inside docker container.
many Thx - this module is really great!!!

**Comment by Lucas-C** [comment]
If you want to install my fork that includes this fix, you can do this:

    pip install git+git://github.com/Lucas-C/pyfpdf.git@master

**Comment by alexanderankin** [comment]
Believe this is also fixed in mine pip install pyfpdf2

**Comment by Lucas-C** [comment]
I confirm this is fixed in https://pypi.org/project/fpdf2/
