### ISSUE TITLE
implement the format parameter for add_page

### ISSUE THREAD

**Issue by whit537** [reingart/pyfpdf#17]
The [docs](https://github.com/reingart/pyfpdf/blob/353a421e4f35e154e4ff714c0d8e911bcde07443/docs/reference/AddPage.md) half-suggest that `add_page` takes a `format` parameter, but I don't find it [in the source](https://github.com/reingart/pyfpdf/blob/353a421e4f35e154e4ff714c0d8e911bcde07443/fpdf/fpdf.py#L258).

**Comment by whit537** [comment]
Ah, looks like it's in the [constructor](https://github.com/reingart/pyfpdf/blob/353a421e4f35e154e4ff714c0d8e911bcde07443/fpdf/fpdf.py#L53), sorry.

**Comment by RomanKharin** [comment]
Chad, i should apologies. This inconviece in documentation will be fixed asap.
Althought we can reopen issue as feature request. What you mind?
PS original fpdf supports this.

**Comment by whit537** [comment]
Sure, we can use this ticket for a feature request. Thanks @RomanKharin! :-)
