### ISSUE TITLE
image ignoring EXIF Rotation

### ISSUE THREAD

**Issue by vALT0r** [reingart/pyfpdf#179]
When I include an image it gets rotated, I believe its because its ignoring EXIF Rotation TAG

**Comment by Lucas-C** [comment]
This project is not maintained anymore, _cf._ https://github.com/reingart/pyfpdf/issues/171

However you could suggest this feature to https://github.com/PyFPDF/fpdf2

**Comment by vALT0r** [comment]
Thanks, I will try that and see if it's fixed there.
