### ISSUE TITLE
Generating a BytesIO with FPDF.output

### ISSUE THREAD

**Issue by vyscond** [reingart/pyfpdf#19]
I've tried all the options over the __FPDF.output__ to produce an valid output to send as a web response using Django's HttpResponse object.

With the String (S) option i can generate a blank PDF and with all the other options the browser just render a grey background and the message of "Loading" (using chrome for testing).

So i was thinking if it's possible to have another type of  __dest__ over the __output__ function to generate an BytesIO object. With this format it's (simple to embed)[https://docs.djangoproject.com/en/1.7/howto/outputting-pdf/#complex-pdfs] it to the response on Django.

**Comment by vyscond** [comment]
```python
def output(self, name='',dest='',verbose=None):
        "Output PDF to some destination"
        #Finish document if necessary
        if(self.state<3):
            self.close()
        
        dest=dest.upper()
        
        if(dest==''):
            if(name==''):
                name='doc.pdf'
                dest='I'
            else:
                dest='F'
        # -----------------
        import io
        if dest == 'B' : # something like that :)
            return bytes(self.buffer,'latin1')

        if dest=='I':
            print(self.buffer)
        elif dest=='D' :
            print(self.buffer)
        elif dest=='F':
            #Save to local file
            f=open(name,'wb')
            if(not f):
                self.error('Unable to create output file: '+name)
            if PY3K:
                # manage binary data as latin1 until PEP461 or similar is implemented
                f.write(self.buffer.encode("latin1"))
            else:
                f.write(self.buffer)
            f.close()
        elif dest=='S':
            #Return as a string
            return self.buffer
        else:
            self.error('Incorrect output destination: '+dest)
        return ''
```

**Comment by RomanKharin** [comment]
Ramon. There are fix for that, i thought.
https://github.com/reingart/pyfpdf/pull/14

**Comment by vyscond** [comment]
true, and i'am using py3 but it's not working here as it should be.

**Comment by vadmium** [comment]
It looks like your suggested output() method is based of the old code before my #14 fix. Perhaps try pulling the latest code from Git Hub. Beware that the Google Code version is out of date, and I think we are migrating away from Google. With my fix you should be able to do this in Python 3:

```python
byte_string = pdf.output(dest="S")  # Probably what you want
stream = BytesIO(byte_string)  # If you really need a BytesIO
```

**Comment by vyscond** [comment]
i see your point. but i installed it using pip .-. should it be with the fix? anyway i will close the issue :) thanks guys!

**Comment by vadmium** [comment]
I’m not really familiar with pip, but the fix is _not_ in the latest 1.7.2 release because it is so recent.

**Comment by msropp** [comment]
Almost 4 years later and the version of fpdf installed by pip is still 1.7.2, so this fix isn't present...

**Comment by alexanderankin** [comment]
im not the best maintainer, but if someone puts a patch about this on my fork ill update it, ive updated upon request before... https://github.com/alexanderankin/pyfpdf `pip install fpdf2`

**Comment by msropp** [comment]
Thanks, maybe I need fpdf2 instead of a fpdf.      In the meantime, I was able to work around it by taking the normal string returned in Python 3 by `pdf.output(dest="S")` and encoding it with bytearray()

**Comment by ghost** [comment]
you guys can sure install it using pip and git URLs with tags

**Comment by emersonhsieh** [comment]
@alexanderankin Your fork works, thank you!
