### ISSUE TITLE
AttributeError: 'FPDF' object has no attribute 'set_creation_date'

### ISSUE THREAD

**Issue by eggnstone** [reingart/pyfpdf#200]
The method `set_creation_date` seems to be available but using it gives the following error:
`AttributeError: 'FPDF' object has no attribute 'set_creation_date'`

Reproduction:
````
pdf = FPDF()
pdf.set_creation_date(datetime(1970, 1, 1))
````

**Comment by Lucas-C** [comment]
`pyfpdf` is not maintained anymore, have you tried using `fpdf2`?
https://pyfpdf.github.io/fpdf2/

**Comment by eggnstone** [comment]
> `pyfpdf` is not maintained anymore, have you tried using `fpdf2`? https://pyfpdf.github.io/fpdf2/

Thanks, I wasn't aware of that!
