### ISSUE TITLE
multi_cell line breaking tolerance

### ISSUE THREAD

**Issue by danieloliveira56** [reingart/pyfpdf#203]
Hi, 

I'm calling `multi_cell` for a simple word (no spaces or `\n`), with argument `w=get_string_width(w)+2*c_margin`, so in theory, I shouldn't see line breaks.

But I'm seeing a line break caused by numerical errors: `1610.99999 < 1611`

![image](https://user-images.githubusercontent.com/5332622/184174121-78c67c3c-c040-48f0-93cf-2fa35c63920e.png)
![image](https://user-images.githubusercontent.com/5332622/184174309-6c9d92a1-60f0-4d46-bffe-7976d0f067a8.png)

I can easily fix this on my side by adding a small value for w. Do you think it is relevant to update multi_cell to either:
- Have a tolerance when comparing `l>wmax`, or
- Have a bool argument, say `automatic_width_line_break`, telling if automatic line breaks based on `txt` width should be performed.

The first option is tricky since different values require different tolerances and choosing a value that always works is hard. The second option is what I would choose. Just lets the user skip line breaking if he's sure the text will fit.

I can create a PR if anyone finds this will be useful.

**Comment by Lucas-C** [comment]
`pyfpdf` is not maintained anymore, have you tried using `fpdf2`?
https://pyfpdf.github.io/fpdf2/

**Comment by danieloliveira56** [comment]
Thanks, I figured I should be using a cell instead of a multi_cell if I'm sure the string will fit.
