### ISSUE TITLE
How to set SYSTEM_TTFONTS ?

### ISSUE THREAD

**Issue by dschiller** [reingart/pyfpdf#204]
This doesn't work:

```python
import fpdf
from fpdf import FPDF

FPDF.SYSTEM_TTFONTS = R'C:\Windows\Fonts'

book = FPDF()

book.add_page()
book.set_font('Caladea', 'R', 17)
book.text(10, 10, 'Test Text')

book.output('Book.pdf', 'F')
```

Error:

```bash
Traceback (most recent call last):
  File "F:\Work\writer.py", line 8, in <module>
    book.set_font('Caladea', 'R', 17)
  File "F:\Work\.venv\lib\site-packages\fpdf\fpdf.py", line 603, in set_font
    self.error('Undefined font: '+family+' '+style)
  File "F:\Work\.venv\lib\site-packages\fpdf\fpdf.py", line 227, in error
    raise RuntimeError('FPDF error: '+msg)
RuntimeError: FPDF error: Undefined font: caladea R
```

![grafik](https://user-images.githubusercontent.com/3144986/194763203-1021cc94-7e9e-4c34-bae5-1831aa0faa30.png)

**Comment by dschiller** [comment]
Also tried those:
```python
fpdf.set_global('SYSTEM_TTFONTS', R'C:\Windows\Fonts')
fpdf.SYSTEM_TTFONTS = R'C:\Windows\Fonts'
SYSTEM_TTFONTS = R'C:\Windows\Fonts'
```
but none is working, same error.

**Comment by dschiller** [comment]
Also tried to use the ttf font name directly:

```python
book.set_font('Caladea-Regular', 'R', 17)
```
![grafik](https://user-images.githubusercontent.com/3144986/194764551-e27717f2-0cc2-4546-a050-1d706ca0414b.png)

But same error:

```python
RuntimeError: FPDF error: Undefined font: caladea-regular R
```

**Comment by dschiller** [comment]
You have a test at https://github.com/reingart/pyfpdf/blob/cb3340806c140b6e63eb4ce9d6230be84fba456e/tests/cover/test_winfonts.py, wonder if that passes ?

**Comment by dschiller** [comment]
It is mandatory to add a font ! Otherwise it's not available.

Working example:

```python
import fpdf
from fpdf import FPDF

fpdf.SYSTEM_TTFONTS = R'C:\Windows\Fonts'

book = FPDF()

book.add_page()
# Use `dir` in folder `C:\Windows\Fonts` to get the font file names
book.add_font('Caladea','R','Caladea-Regular.ttf',uni=True)
book.set_font('Caladea', 'R', 17)
book.text(10, 10, 'Test Text')

book.output('Book.pdf', 'F')
```

**Comment by Lucas-C** [comment]
`pyfpdf` is not maintained anymore, have you tried using `fpdf2`?
https://pyfpdf.github.io/fpdf2/

It does not support `SYSTEM_TTFONTS` however, full paths must be provided to its [add_font()](https://pyfpdf.github.io/fpdf2/fpdf/fpdf.html#fpdf.fpdf.FPDF.add_font) method
