### ISSUE TITLE
Cannot encode fancy characters into PDF

### ISSUE THREAD

**Issue by johnerinjery** [reingart/pyfpdf#210]
So some of the text I want in my PDF contains special "fancy" characters like these :  `‘ ’ ´ “ ” – - ― 　–` 
When I'm trying to have them in my PDF Its giving me gibberish text in place of these characters. Any workaround?

**Comment by andersonhc** [comment]
PyFPDF is not maintained anymore.
fpdf2 is its successor: https://pypi.org/project/fpdf2/

**Comment by johnerinjery** [comment]
Ahh is that so, I'll look into that then thanks!
