### ISSUE TITLE
Storage for project artifacts (fonts, images, etc)

### ISSUE THREAD

**Issue by RomanKharin** [reingart/pyfpdf#25]
Currently we use some data on external server and not in repository:

* fpdf_unicode_font_pack.zip - 15.7Mb, fonts used by tests, tutorials, examples
* tuto*.pdf - approximately 100Kb, PDF samples
* perhaps something other

This files server from googlecode, which will be closed for changing. Github doesn't provide space for binary storage.

Any proposes?

**Comment by vyscond** [comment]
Maybe this could be a start https://help.github.com/articles/distributing-large-binaries/

**Comment by RomanKharin** [comment]
It would be wrong to load in repository 15Mb binary blob.

**Comment by reingart** [comment]
The releases it could be used to upload binaries: https://github.com/reingart/pyfpdf/releases
There is any problem with that?

**Comment by RomanKharin** [comment]
Seems to can be 
> If you'd like to include binary files along with your release, such as compiled programs, drag and drop or select files manually in the binaries box. 
But, in reality
> Unfortunately, we don't support that file type. Try zipping it. 
fpdf_unicode_font_pack.zip

**Comment by RomanKharin** [comment]
Sorry for inconvenience, after page reload error disappeared.

**Comment by RomanKharin** [comment]
As googlecode is down now i close this issue.
