### ISSUE TITLE
3 columns with multi_cell

### ISSUE THREAD

**Issue by vyscond** [reingart/pyfpdf#27]
i tried with
```python
pdf.multi_cell(40,10,'column 1',1,0,'C')
pdf.multi_cell(40,10,'column 1',1,0,'C')
pdf.multi_cell(70,10,'column 1',1,0,'C')
```
but the cells appeared one below the other

How can i make three columns (side-by-side) with __multi_cell__?

**Comment by eocasio** [comment]
Here is a gist to give you an idea of what is involved: https://gist.github.com/eocasio/32a5d8c7079b7c0c87c8

**Comment by vyscond** [comment]
yup. i got something like that too! :D
