### ISSUE TITLE
rotate function not listed over the documentation

### ISSUE THREAD

**Issue by vyscond** [reingart/pyfpdf#33]
Why rotate function is not on the documentation?

**Comment by RomanKharin** [comment]
This function provide some low-level actions, and required manual align and hyphenations of the text.
Also i didn't check edge-cases well.
If someone can describe this, you are welcome.

**Comment by vyscond** [comment]
Ok, i can do that, but not right now! So if no one has done before I get a free time will post the possible documentation

**Comment by alekssaff** [comment]
This script allows to perform a rotation around a given center.
The method to set a rotation is:

rotate(float angle [, float x [, float y]])

angle: angle in degrees.
x: abscissa of the rotation center. Default value: current position.
y: ordinate of the rotation center. Default value: current position.

The rotation affects all elements which are printed after the method call (with the exception of clickable areas).

Remarks:

- Only the display is altered. The get_x() and get_y() methods are not affected, nor the automatic page break mechanism.
- Rotation is not kept from page to page. Each page begins with a null rotation.

**Comment by RomanKharin** [comment]
Ok. I'll add this to reference, but with note about this api function is not final.
