### ISSUE TITLE
Auto page break margin - html table borders.

### ISSUE THREAD

**Issue by lwhistler** [reingart/pyfpdf#38]
Two questions:

1. I can't adjust the bottom margin with pdf.set_auto_page_break(auto: bool, margin = 0.0). It crashes the script, what is the proper syntax?

2. The html table has a line at top and bottom, I do not want any borders. How do I eliminate the top and bottom lines?

Thanks.

**Comment by RomanKharin** [comment]
1. Documentation are made with PEP-484 in mind. This cause syntax error in old python interpreters. Ignore part after ":".

**Comment by lwhistler** [comment]
This works for the top margin:  pdf.set_top_margin(margin=20)
But this doesn't work for the bottom:  pdf.set_auto_page_break(margin=25)

**Comment by RomanKharin** [comment]
But `auto` parameter for `set_auto_page_break` function are mandatory.

**Comment by lwhistler** [comment]
Still doesn't work. :(

pdf.set_auto_page_break(auto, margin=25)

**Comment by vadmium** [comment]
Some more information on the crashes would be nice. What is the exception message? What is the value of “auto” you are passing in?

**Comment by lwhistler** [comment]
I don't  get any messages,  the terminal window closes, when it should stay open. What should the value of auto be? I have never seen a working example so I refer to the manual and it has this:

pdf.set_auto_page_break(auto: bool, margin = 0.0)

What choices are there for bool?

**Comment by vadmium** [comment]
Oh I see. I guess you aren’t too familiar with the Python language. :) bool can be True or False, so you probably want something like this (untested):

```python
pdf.set_auto_page_break(True, 25)
```

Also, it sounds like you might be running the script from a simple file manager GUI or something. You might have more luck seeing error messages if you run the script from a shell inside a terminal instead.

**Comment by lwhistler** [comment]
Thanks vadmium, your syntax works 100% It's a little different than the top margin syntax, so I couldn't figure it out.

pdf.set_top_margin(margin=18)
pdf.set_auto_page_break(True, 25)

And yes I'm new to Python. I'm on Linux and I hand code with Pluma 1.81 and make the file executable - then double click to run. The terminal stays open if everything is OK, closes if there is an error.

My project is to take a CSV file directly to PDF - and avoid the spreadsheet step. I'm 100% happy with Pyfpdf - the HTML tables is very good. Thanks again for the help.
