### ISSUE TITLE
Image breaks PDF

### ISSUE THREAD

**Issue by bouldrini** [reingart/pyfpdf#76]
Since im using version 1.7.2 installed from github the pdf.image method breaks the PDF without throwing an exception or any other traceable error. All I get is:

Couldn’t open PDF
Something’s keeping this PDF from opening.

when i attemb to open the PDF.

This was working with version 1.7.2 installed via PIP, which doesn't provide an add_page method with format parameter, what is the reason why i have to use the github installation.

help ?
best regards

**Comment by RomanKharin** [comment]
bouldrini, can you provide test code and image sample?

**Comment by bouldrini** [comment]
Fast reply, good work.
Here some code + the image i want to show:

        self.m_pdf.add_page("portrait", "A4")
        self.m_pdf.set_font('Arial', '', 10)
        self.m_pdf.cell(40, 10, '')
        self.m_pdf.image("images\\bitXplorer_logo_neu_klein.png", 10, 10, 33)
        self.m_pdf.output(self.m_output_directory + "testreport.pdf", 'F')

![bitxplorer_logo_neu_klein](https://cloud.githubusercontent.com/assets/2077513/21801469/16f4cf34-d722-11e6-9fd2-4fa311344ccf.png)

**Comment by bouldrini** [comment]
nevermind, this is not an issue caused by FPDF, it is caused by the awesome Microsoft Edge PDF viewer.
Firefox displays it correctly.

Thanks for your support anyway.
Ill close the issue

**Comment by RomanKharin** [comment]
bouldrini, can you test master. We fix bug #78 with RGBA images, that trigger in some viewers/
