### ISSUE TITLE
Imprimir 2 hojas A5 en una A4

### ISSUE THREAD

**Issue by injaon** [reingart/pyfpdf#77]
Estimados, estoy trabajando en un proyecto que imprimie docuemtos en A5. El papel que voy a usar es A4 y en la mitad esta troquelado para que el usuario final lo pueda cortar. Como mi aplicacion imprimite en A5 en duplicado, busco que emita dos paginas A5 en una hoja A4. Es posible? me puedan dar un orientacion?

Desde ya muchas gracias.

**Comment by ejmvar** [comment]
Hubo alguien, hace cosa de un año, que envió es misma solución.
No tengo acceso para buscarlo ahora, pero está en las listas de pyafip.
Espero la encuentres.

Eduardo.

**Comment by injaon** [comment]
Muchas gracias por responder Eduardo. No lo puede encontrar pero comparto mi solución: *Utilize  PyPDF2 para concatenar dos archivos iguales.*

En la introduccion de `fpdf` dice muy claramente que no es una libreria de manipulacion de archivos, asi que quizas este no haya sido el mejor lugar para realizar mi pregunta, De cualquier manera, el fpdf de PHP tiene una funcionalidad [similar](http://www.fpdf.org/en/script/script94.php) que estaria bueno portar.

Saludos.
