### ISSUE TITLE
PDF files generated cannot be read by Adobe Reader or Preview on Mac

### ISSUE THREAD

**Issue by youralien** [reingart/pyfpdf#78]
Attached is an output pdf generated by doing a series of add_page() and image() calls.  I cannot open the PDF successfully in programs like Adobe Reader or Preview on MacOS, but can open them with evince in Linux and the PDF viewer in Google Chrome.  Does any one know what might be causing this issue?

Here is the code I am using, in which I am passing a list of *.png files

```
def makePdf(out_path, listImages, dir = ''):
    """
    Arguments
    ---------
    out_path: str, i.e. 'path/to/output.pdf'
    listImages: list of str, i.e. ['road_user_type_counts.png', 'speed_cdf.png']
    dir: str, path where images located, and pdf will be outputted
    """

    pdf = FPDF(orientation='L', unit = "in", format = 'Letter')

    # Save an image per page
    for page in listImages:
        pdf.add_page()

        img_path = os.path.join(dir,str(page))
        img = Image.open(img_path)
        w, h = img.size
        
        # all images default 8 inch width
        width = 8

        # height in inches, relative to aspect ratio
        height = width * (h // w)

        pdf.image(img_path, x=1, y=1, w=width, h=height)

    pdf.output(out_path, "F")
```

[santosreport.pdf](https://github.com/reingart/pyfpdf/files/756138/santosreport.pdf)

**Comment by RomanKharin** [comment]
Something strange with you images
1. AdobeReader 11 (win) - works
2. Evince 3.18.2 - works
3. Chrome 56.0 PDF viewer (win, lin) - works
4. LibreOffice - fail IO error
5. PDFSam 2.2 - error

Can you send me original image files?

Also, please test this PDF from out stock images
[issue_78.pdf](https://github.com/reingart/pyfpdf/files/757024/issue_78.pdf)

**Comment by youralien** [comment]
The following are the original image files.
![road_user_icon_counts](https://cloud.githubusercontent.com/assets/5459644/22693366/006d0966-ed11-11e6-90d4-e5edb196a87c.png)
![velocitycdf](https://cloud.githubusercontent.com/assets/5459644/22693369/04adf206-ed11-11e6-817e-9ad61b993915.png)

issue_78.pdf file was able to open in Preview on MacOS.

**Comment by RomanKharin** [comment]
Ah, confirm bug
Image files with rgb and alpha cause such problem. Indexed with alpha - can't.

**Comment by youralien** [comment]
Great I will try to generate images with not alpha channel.  Should I close this issue then?

**Comment by RomanKharin** [comment]
I will investigate this issue and close if required.
