### ISSUE TITLE
Where to add unicode Fonts?

### ISSUE THREAD

**Issue by clpatterson** [reingart/pyfpdf#98]
I'm trying to add a new unicode font so I can use Chinese characters. I've added fireflysung.ttf to the font directory in attic, but fpdf.py can't seem to find the file ('RuntimeError: TTF Font file not found: fireflysung.ttf'). When I look on github I saw that the attic directory is full of things that are no longer supported. Couldn't find any other font directory. Where does my ttf file go?

**Comment by eocasio** [comment]
You must add the new font to the document using an absolute path. Try this:

```python
# Add font from system. Font file path must be specified if it is not
# in an accesible path to pyFPDF.
# Second parameter is always empty for backward compatibility.
# uni=True enables Unicode
pdf.add_font('YOUR_TTF_FONT','','/usr/share/fonts/truetype/YOUR_TTF_FONT.ttf', uni=True)

# Set font family, 'U'nderlined, size 14.0 pt
pdf.set_font('YOUR_TTF_FONT','U',14.0)
pdf.cell(1.0,0.0,'Hello World!')
```
Edit: Used generic name for example font.

**Comment by RomanKharin** [comment]
Please DO NOT use comic sans font under any circumstances. It is not free.

**Comment by clpatterson** [comment]
Great, thanx!
